version: "3"
services:
  app:
    container_name: appUser
    restart: always
    build: .
    ports:
      - "8081:8081"
    links:
      - mongo
  mongo:
    container_name: mongoDBUser
    image: mongo
    ports:
      - "27017:27017"